$d = "C:\Users\miboutros\OneDrive - Deloitte (O365D)\Scripts\GenerateReleaseNotes\TestResult"
$env:SYSTEM_DEFAULTWORKINGDIRECTORY = "$d"
$env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI = "http://tfsabs.sltc.com:8080/tfs/DefaultCollection/"
$env:SYSTEM_TEAMPROJECT = "ABSSuite Web"
$env:RELEASE_RELEASEID = "26345"
$env:RELEASE_DEFINITIONID = "20"
$env:RELEASE_ENVIRONMENTNAME = "Test.RMB"
$env:BUILD_BUILDID = "38844"
$env:BUILD_DEFINITIONNAME = "ABS-Sprint-11.12"
$env:RELEASE_DEFINITIONNAME = "AR.Rmb"
$env:BUILD_BUILDNUMBER = "11.12.111 - 20191120.38894"
$env:Ver = "11.12.111"
Write-Host "Ver $env:Ver" 
$VerbosePreference = "Continue"
.\GenerateReleaseNotes.ps1 -outputfile "$d\rd.md"  -publishLoc "$d\pub\" -notesRootPath "$d\root" -templateLocation "File" -templatefile "$d\RNTemplate.txt" -emptySetText "None" -generateForOnlyPrimary $false -usedefaultcreds $true -generateForCurrentRelease $false -maxWi 500 -maxChanges 500 -appendToFile $false -showParents $true -wiFilter "Bug,PRODUCT BACKLOG ITEM,Feature,Epic" -unifiedList $true -outputvariablename "ReleaseNotesTotal" ## -overrideStartReleaseId 26111 